### ISSUE TITLE
When multiple subtags are named the same but are in different nested tags, clicking one will show/hide all the others ones as well

### ISSUE THREAD

**Issue by kael-shipman** [kael-shipman/swagger-ui-plugins#2]
Reported by @chesiren:

> When multiple subtags are named the same but are in different nested tags, clicking one will show/hide all the others ones as well. You can see the problem in the petstore example included in your plugin package by clicking the view,create or delete tags (or video below to show the problem)
>
> https://user-images.githubusercontent.com/44122832/213244155-1886039c-ae14-4b76-9a0e-ceaf27147f46.mp4

**Comment by TiagoRibeiro-hub** [comment]
H @kael-shipman, do you have any predictions as to when this problem will be solved?

**Comment by kael-shipman** [comment]
Haha no, sorry. I'm dealing with a ton of "extracurriculars" right now, so time is short! However, things may be cooling down a bit in the next few weeks, and I believe this will be a really easy fix once I get back into the codebase and remember how it all works. All that to say, I hope to get to it within the next month, but no guarantees.

**Comment by TiagoRibeiro-hub** [comment]
Ok. Thank you.

**Comment by kael-shipman** [comment]
Yaaay, I finally found time to fix this! I also added a new config option, `hierarchicalTagSeparator`, in case you want to change the separator character (see the readme for details).
